parameters:
    # PDF of content available
    pdf_available: [ 13, 17 ]

ezplatform:
    system:
        site:
            languages: [eng-US]
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [770] }


ezdesign:
    design_list:
        site_design: [site_design]
    templates_theme_paths:
        site_design:
            - '%kernel.project_dir%/templates/views/themes/site_design'
    templates_override_paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/templates/views/themes/site_design'

ezpublish:
    system:
        default:
            pagelayout: '@ezdesign/pagelayout.html.twig'
        site_group:
            design: site_design
            content_view:
                line:
                    article:
                        template: '@ezdesign/line/article.html.twig'
                        match:
                            Identifier\ContentType: [article]
                full:
                    sign:
                        template: '@ezdesign/full/sign.html.twig'
                        match:
                            Id\Content: 61
                        controller: ez_query:locationQueryAction
                        params:
                            query:
                                query_type: LocationChildren
                                parameters:
                                    parentLocationId: '@=location.id'
                                assign_results_to: items
                    course:
                        controller: App\Controller\DefaultController::courseViewEnhancedAction
                        template: '@ezdesign/full/course.html.twig'
                        match:
                            Identifier\ContentType: [course]
                    department:
                        template: '@ezdesign/full/department.html.twig'
                        match:
                            Identifier\ContentType: [department,program]
                        controller: ez_query:locationQueryAction
                        params:
                            query:
                                query_type: LocationChildren
                                parameters:
                                    parentLocationId: '@=location.id'
                                assign_results_to: items
                    folder:
                        template: '@ezdesign/full/folder.html.twig'
                        match:
                            Identifier\ContentType: [folder]
                        controller: ez_query:locationQueryAction
                        params:
                            query:
                                query_type: LocationChildren
                                parameters:
                                    parentLocationId: '@=location.id'
                                assign_results_to: items
                    syllabus:
                        controller: App\Controller\DefaultController::syllabusViewEnhancedAction
                        template: '@ezdesign/full/syllabus.html.twig'
                        match:
                            Identifier\ContentType: [syllabus]
                        params:
                            availableSupportServicesId: 70
                            collegePoliciesId: 52
                            diversityEquityAndInclusionId: 181
                            gradingSchemeId: 85
                            technologyId: 180
