#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pdf:
     path: /pdf/{path}
     controller: App\Controller\PdfController::pdfViewAction
     requirements:
        path: .+

